/** Thème EL MECANO — aligné menu sombre + accent orange (véhicules). */
export const theme = {
  bg: '#f3f4f6',
  surface: '#ffffff',
  surfaceMuted: '#f9fafb',
  border: '#e5e7eb',
  borderLight: '#f3f4f6',
  text: '#111827',
  textSecondary: '#374151',
  textMuted: '#6b7280',
  textSubtle: '#9ca3af',
  dark: '#111827',
  headerBg: '#030712',
  primary: '#f97316',
  primaryDark: '#ea580c',
  primarySoft: '#fff7ed',
  success: '#22c55e',
  successSoft: '#ecfdf5',
  danger: '#ef4444',
  dangerSoft: '#fef2f2',
  radius: { sm: 12, md: 14, lg: 16, pill: 999 },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    fab: {
      shadowColor: '#f97316',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 6,
    },
    primaryBtn: {
      shadowColor: '#f97316',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 3,
    },
  },
} as const
